source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

platform :ios, '13.0'

target "News App" do

    pod 'SDWebImage'
    pod 'MBProgressHUD'
    pod 'Masonry'
    pod 'Mantle'
    pod 'XLForm'
    pod 'AFNetworking'
end
